const { withFinalizedMod } = require('@expo/config-plugins')
const fs = require('fs')
const path = require('path')

/**
 * Points windowSplashScreenAnimatedIcon to the full adaptive icon (background + foreground)
 * instead of the foreground-only splashscreen_logo generated by expo-splash-screen.
 *
 * Uses withFinalizedMod so it runs AFTER all other mods (including expo-splash-screen's
 * withAndroidStyles which adds the splashscreen_logo reference).
 */
const withAdaptiveIconSplashScreen = (config) =>
  withFinalizedMod(config, [
    'android',
    (mod) => {
      const stylesPath = path.join(
        mod.modRequest.platformProjectRoot,
        'app', 'src', 'main', 'res', 'values', 'styles.xml'
      )
      if (fs.existsSync(stylesPath)) {
        const content = fs.readFileSync(stylesPath, 'utf8')
        const updated = content.replace(
          /@drawable\/splashscreen_logo/g,
          '@drawable/animated_logo'
        )
        if (updated !== content) {
          fs.writeFileSync(stylesPath, updated, 'utf8')
        }
      }
      return mod
    }
  ])

module.exports = withAdaptiveIconSplashScreen
